### ISSUE TITLE
Error after upgrade to 5.29.0: java.lang.NoSuchMethodError: 'void org.springframework.http.HttpEntity.<init>(java.lang.Object, org.springframework.http.HttpHeaders)'

### ISSUE THREAD

**Issue by adamandre79** [SAP/cloud-sdk-java#1165]
### Describe the Bug

Hello,

we are using the following parent:

```
    <parent>
        <groupId>com.sap.sgs</groupId>
        <artifactId>security-patched-spring-boot-starter</artifactId>
        <version>3.5.14-sap-01</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
```

after upgrading from `5.28.0` to `5.29.0` for this bom:

```
            <dependency>
                <groupId>com.sap.cloud.sdk</groupId>
                <artifactId>sdk-bom</artifactId>
                <version>${sap.cloud.sdk.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
```

we get the error:
```
 java.lang.NoSuchMethodError: 'void org.springframework.http.HttpEntity.<init>(java.lang.Object, org.springframework.http.HttpHeaders)'                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                    
      at com.sap.cloud.security.xsuaa.client.XsuaaOAuth2TokenService.executeRequest(XsuaaOAuth2TokenService.java:77)                                                                                                                                                                                                
      at com.sap.cloud.security.xsuaa.client.XsuaaOAuth2TokenService.requestAccessToken(XsuaaOAuth2TokenService.java:60)                                                                                                                                                                                            
      at com.sap.cloud.security.xsuaa.client.AbstractOAuth2TokenService.getAndCacheToken(AbstractOAuth2TokenService.java:289)                                                                                                                                                                                       
      at com.sap.cloud.security.xsuaa.client.AbstractOAuth2TokenService.getOrRequestAccessToken(AbstractOAuth2TokenService.java:248)                                                                                                                                                                                
      at com.sap.cloud.security.xsuaa.client.AbstractOAuth2TokenService.getOAuth2TokenResponse(AbstractOAuth2TokenService.java:231)                                                                                                                                                                                 
      at com.sap.cloud.security.xsuaa.client.AbstractOAuth2TokenService.retrieveAccessTokenViaClientCredentialsGrant(AbstractOAuth2TokenService.java:113)                                                                                                                                                           
      at com.sap.cloud.security.xsuaa.tokenflows.ClientCredentialsTokenFlow.execute(ClientCredentialsTokenFlow.java:146)                                                                                                                                                                                            
      at com.sap.grc.automatedprocedures.api.rest.outbound.common.resttemplate.DefaultRestTemplateFactory$ClientCredentialsJwtInterceptor.intercept(DefaultRestTemplateFactory.java:183)                                                                                                                            
      at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:88)                                                                                                                                                                  
      at com.sap.grc.automatedprocedures.api.rest.outbound.common.resttemplate.DefaultRestTemplateFactory.lambda$getLoggingInterceptor$1(DefaultRestTemplateFactory.java:119)                                                                                                                                       
      at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:88)                                                                                                                                                                  
      at com.sap.grc.automatedprocedures.api.rest.outbound.common.resttemplate.DefaultRestTemplateFactory$DefaultHeadersInterceptor.intercept(DefaultRestTemplateFactory.java:171)                                                                                                                                  
      at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:88)                                                                                                                                                                  
      at org.springframework.http.client.InterceptingClientHttpRequest.executeInternal(InterceptingClientHttpRequest.java:72)                                                                                                                                                                                       
      at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)                                                                                                                                                                             
      at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:81)                                                                                                                                                                                                       
      at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:900)                                                                                                                                                                                                                               
      at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:841)                                                                                                                                                                                                                                 
      at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:702)                                                                                                                                                                                                                                
      at com.sap.grc.automatedprocedures.api.rest.outbound.common.DefaultRetryableRestClient.lambda$executeRequest$0(DefaultRetryableRestClient.java:73)                                                                                                                                                            
      at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:357)                                                                                                                                                                                                                          
      at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:230)                                                                                                                                                                                                                            
      at com.sap.grc.automatedprocedures.api.rest.outbound.common.DefaultRetryableRestClient.executeRequest(DefaultRetryableRestClient.java:72)                                                                                                                                                                     
      at com.sap.grc.automatedprocedures.api.rest.outbound.common.DefaultRetryableRestClient.postAndLog(DefaultRetryableRestClient.java:44)                                                                                                                                                                         
      at com.sap.grc.automatedprocedures.api.rest.outbound.capsidecar.communication.SidecarApiCallerBase.postExtensionCreation(SidecarApiCallerBase.java:32)                                                                                                                                                        
      at com.sap.grc.automatedprocedures.api.rest.outbound.capsidecar.communication.MtxsFileBasedApiCaller.postExtensionCreation(MtxsFileBasedApiCaller.java:12)                                                                                                                                                    
      at com.sap.grc.automatedprocedures.api.rest.outbound.capsidecar.communication.SidecarApiCallerBase.postExtensionCreation(SidecarApiCallerBase.java:29)                                                                                                                                                        
      at com.sap.grc.automatedprocedures.api.rest.outbound.capsidecar.communication.MtxsFileBasedApiCaller.postExtensionCreation(MtxsFileBasedApiCaller.java:12)                                                                                                                                                    
      at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)                                                                                                                                                                                                      
      at java.base/java.lang.reflect.Method.invoke(Method.java:580)                                                                                                                                                                                                                                                 
      at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:360)                                                                                                                                                                                                                 
      at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)                                                                                                                                                                                          
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)                                                                                                                                                                                                  
      at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:64)                                                                                                                                                                                                      
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)                                                                                                                                                                                                  
      at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)                                                                                                                                                                                                
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)                                                                                                                                                                                                  
      at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:728)                                                                                                                                                                                                
      at com.sap.grc.automatedprocedures.api.rest.outbound.capsidecar.communication.MtxsFileBasedApiCaller$$SpringCGLIB$$0.postExtensionCreation(<generated>)                                                                                                                                                       
      at com.sap.grc.automatedprocedures.api.rest.outbound.capsidecar.SidecarArtifactGenerator.generate(SidecarArtifactGenerator.java:46)                                                                                                                                                                           
      at com.sap.grc.automatedprocedures.api.rest.outbound.capsidecar.SidecarArtifactGenerator.generate(SidecarArtifactGenerator.java:39)                                                                                                                                                                           
      at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)                                                                                                                                                                                                      
      at java.base/java.lang.reflect.Method.invoke(Method.java:580)                                                                                                                                                                                                                                                 
      at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:360)                                                                                                                                                                                                                 
      at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)                                                                                                                                                                                          
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)                                                                                                                                                                                                  
      at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:64)                                                                                                                                                                                                      
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)                                                                                                                                                                                                  
      at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)                                                                                                                                                                                                
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)                                                                                                                                                                                                  
      at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:728)                                                                                                                                                                                                
      at com.sap.grc.automatedprocedures.api.rest.outbound.capsidecar.SidecarArtifactGenerator$$SpringCGLIB$$0.generate(<generated>)                                                                                                                                                                                
      at com.sap.grc.automatedprocedures.businesslogic.core.generation.DefaultResultStorageCreator.createNewArtifacts(DefaultResultStorageCreator.java:41)                                                                                                                                                          
      at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)                                                                                                                                                                                                      
      at java.base/java.lang.reflect.Method.invoke(Method.java:580)                                                                                                                                                                                                                                                 
      at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:360)                                                                                                                                                                                                                 
      at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)                                                                                                                                                                                          
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)                                                                                                                                                                                                  
      at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:64)                                                                                                                                                                                                      
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)                                                                                                                                                                                                  
      at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)                                                                                                                                                                                                
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)                                                                                                                                                                                                  
      at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:728)                                                                                                                                                                                                
      at com.sap.grc.automatedprocedures.businesslogic.core.generation.DefaultResultStorageCreator$$SpringCGLIB$$0.createNewArtifacts(<generated>)                                                                                                                                                                  
      at com.sap.grc.automatedprocedures.businesslogic.core.generation.DefaultResultStorageCreatorIT.sidecarIsCalledCorrectlyForFoundItems(DefaultResultStorageCreatorIT.java:80)                                                                                                                                   
      at java.base/java.lang.reflect.Method.invoke(Method.java:580)                                                                                                                                                                                                                                                 
      at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)                                                                                                                                                                                                                                                 
      at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)    
```

Before it works without problems and we only changed this version.

So what can be the reason?

Regards
André

### Steps to Reproduce

see error logs

### Expected Behavior

error do not occur during runtime

### Screenshots

_No response_

### Used Versions

see description

### Code Examples

```java
// Your code here
```


### Stack Trace

_No response_

### Log File

<details><summary>Log file</summary>
...
</details>


### Affected Development Phase

Production

### Impact

Blocked

### Timeline

_No response_

**Comment by rpanackal** [comment]
We migrated to the [security library](https://github.com/SAP/cloud-security-services-integration-library) version 4.0.3 on our release 5.29.0. As of 4.0.x, they have moved to Spring framework 7 and Spring Boot 4. 

Since you are directly depending on security library and probably running Spring 6 (?) -> the XSUAA client 4.0.3 tries to call a constructor that only exists in Spring 7.x.

Can you share your dependency tree with us so we can confirm?

**Comment by Jonas-Isr** [comment]
We assume that this issue is resolved as there has not been any activity in a week. Feel free to open a new ticket if you have further problems.

Best,
Jonas
