### ISSUE TITLE
NoClassDefFoundError after upgrade to 5.21.0

### ISSUE THREAD

**Issue by yashmeet29** [SAP/cloud-sdk-java#884]
### Describe the Bug

NoClassDefFoundError after upgrade to 5.21.0

### Steps to Reproduce

We are from [SDM CAP plugin](https://github.com/cap-java/sdm) team. Due to vulnerability in dependencies of Cloud SDK commons-lang3, we upgraded cloud-sdk version to 5.21.0 and now on upload of attachments, we are getting NoClassDefFoundError: com/sap/cloud/sdk/cloudplatform/util/StringUtils

2025-08-08T10:40:44.562+0000 [APP/PROC/WEB/0] STDOUT 2025-08-08T10:40:44.561Z  INFO 13 --- [nio-8080-exec-4] c.s.c.s.s.h.SDMAttachmentsServiceHandler : CREATE_ATTACHMENT Event Received with content length 65715 At 1754649644561
2025-08-08T10:40:44.569+0000 [APP/PROC/WEB/0] STDOUT 2025-08-08T10:40:44.568Z  INFO 13 --- [nio-8080-exec-4] c.s.c.a.o.v4.processors.CdsProcessor     : Exception marked the ChangeSet 46 as cancelled: com/sap/cloud/sdk/cloudplatform/util/StringUtils
2025-08-08T10:40:44.574+0000 [APP/PROC/WEB/0] STDOUT 2025-08-08T10:40:44.569Z ERROR 13 --- [nio-8080-exec-4] c.s.c.a.o.v4.processors.CdsProcessor     : com/sap/cloud/sdk/cloudplatform/util/StringUtils
2025-08-08T10:40:44.574+0000 [APP/PROC/WEB/0] STDOUT java.lang.NoClassDefFoundError: com/sap/cloud/sdk/cloudplatform/util/StringUtils
2025-08-08T10:40:44.574+0000 [APP/PROC/WEB/0] STDOUT at com.sap.cloud.sdk.cloudplatform.connectivity.ComplexDestinationPropertyFactory.getHeadersFromProperties(ComplexDestinationPropertyFactory.java:229) ~[cloudplatform-connectivity-5.21.0.jar:na]
2025-08-08T10:40:44.574+0000 [APP/PROC/WEB/0] STDOUT at com.sap.cloud.sdk.cloudplatform.connectivity.DefaultHttpDestination.<init>(DefaultHttpDestination.java:137) ~[cloudplatform-connectivity-5.21.0.jar:na]
2025-08-08T10:40:44.574+0000 [APP/PROC/WEB/0] STDOUT at com.sap.cloud.sdk.cloudplatform.connectivity.DefaultHttpDestination$Builder.buildInternal(DefaultHttpDestination.java:1012) ~[cloudplatform-connectivity-5.21.0.jar:na]
2025-08-08T10:40:44.574+0000 [APP/PROC/WEB/0] STDOUT at com.sap.cloud.sdk.cloudplatform.connectivity.DefaultHttpDestination$Builder.build(DefaultHttpDestination.java:1006) ~[cloudplatform-connectivity-5.21.0.jar:na]
2025-08-08T10:40:44.574+0000 [APP/PROC/WEB/0] STDOUT at com.sap.cds.sdm.handler.TokenHandler.getHttpClient(TokenHandler.java:122) ~[sdm-1.0.0-RC1.jar:na]
2025-08-08T10:40:44.574+0000 [APP/PROC/WEB/0] STDOUT at com.sap.cds.sdm.service.SDMServiceImpl.getRepositoryInfo(SDMServiceImpl.java:466) ~[sdm-1.0.0-RC1.jar:na]
2025-08-08T10:40:44.574+0000 [APP/PROC/WEB/0] STDOUT at com.sap.cds.sdm.service.SDMServiceImpl.checkRepositoryType(SDMServiceImpl.java:443) ~[sdm-1.0.0-RC1.jar:na]
2025-08-08T10:40:44.574+0000 [APP/PROC/WEB/0] STDOUT at com.sap.cds.sdm.service.handler.SDMAttachmentsServiceHandler.validateRepository(SDMAttachmentsServiceHandler.java:147) ~[sdm-1.0.0-RC1.jar:na]
2025-08-08T10:40:44.574+0000 [APP/PROC/WEB/0] STDOUT at com.sap.cds.sdm.service.handler.SDMAttachmentsServiceHandler.createAttachment(SDMAttachmentsServiceHandler.java:65) ~[sdm-1.0.0-RC1.jar:na]

If we downgrade to 5.17.0, this issue is not there. However, 5.17.0 has vulnerability of Cloud SDK commons-lang3.

### Expected Behavior

Post upgrade to 5.21.0, there should not be any failure as it is working in 5.17.0

### Used Versions

- Java and Maven version via `mvn --version`:
Maven home: /Users/I536322/Downloads/apache-maven-3.9.8
Java version: 17.0.16, vendor: SAP SE, runtime: /Library/Java/JavaVirtualMachines/sapmachine-17.jdk/Contents/Home
Default locale: en_IN, platform encoding: UTF-8
OS name: "mac os x", version: "15.6", arch: "aarch64", family: "mac"
- SAP Cloud SDK version: 5.21.0
- CAP version: 3.10.3

<details><summary>Dependency tree via <code>mvn dependency:tree</code></summary>
    
```
com.sap.cds:sdm-root:pom:1.0.0-RC1
[INFO] +- com.sap.cds:cds-services-api:jar:3.10.3:compile
[INFO] |  +- com.sap.cds:cds4j-api:jar:3.10.3:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:2.0.13:compile
[INFO] |  \- com.sap.cloud.environment.servicebinding.api:java-core-api:jar:0.10.5:compile
[INFO] +- org.junit.jupiter:junit-jupiter-api:jar:5.11.3:test
[INFO] |  +- org.opentest4j:opentest4j:jar:1.3.0:test
[INFO] |  +- org.junit.platform:junit-platform-commons:jar:1.11.3:test
[INFO] |  \- org.apiguardian:apiguardian-api:jar:1.1.2:test
[INFO] +- org.assertj:assertj-core:jar:3.27.3:test
[INFO] +- net.bytebuddy:byte-buddy:jar:1.17.1:compile
[INFO] +- net.bytebuddy:byte-buddy-agent:jar:1.17.1:test
[INFO] +- org.mockito:mockito-core:jar:5.15.2:test
[INFO] \- org.apache.httpcomponents:httpmime:jar:4.5.14:compile
[INFO]    \- org.apache.httpcomponents:httpclient:jar:4.5.14:compile
[INFO]       \- org.apache.httpcomponents:httpcore:jar:4.4.16:compile



com.sap.cds:sdm:jar:1.0.0-RC1
[INFO] +- org.apache.httpcomponents.client5:httpclient5:jar:5.4.4:compile
[INFO] |  +- org.apache.httpcomponents.core5:httpcore5-h2:jar:5.3.4:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:2.0.13:compile
[INFO] +- org.apache.httpcomponents.core5:httpcore5:jar:5.3.3:compile
[INFO] +- org.apache.httpcomponents:httpasyncclient:jar:4.1.5:compile
[INFO] |  +- org.apache.httpcomponents:httpcore:jar:4.4.16:compile
[INFO] |  +- org.apache.httpcomponents:httpcore-nio:jar:4.4.15:compile
[INFO] |  \- org.apache.httpcomponents:httpclient:jar:4.5.14:compile
[INFO] +- org.apache.logging.log4j:log4j-api:jar:3.0.0-beta2:compile
[INFO] +- org.projectlombok:lombok:jar:1.18.36:provided
[INFO] +- com.sap.cloud.security.xsuaa:token-client:jar:3.5.7:compile
[INFO] |  \- com.github.ben-manes.caffeine:caffeine:jar:3.2.2:compile
[INFO] |     \- org.jspecify:jspecify:jar:1.0.0:compile
[INFO] +- com.sap.cloud.security:java-api:jar:3.5.8:compile
[INFO] +- com.sap.cloud.environment.servicebinding.api:java-access-api:jar:0.10.5:compile
[INFO] +- com.sap.cloud.environment.servicebinding.api:java-core-api:jar:0.10.5:compile
[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.18.2:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.19.1:compile
[INFO] +- org.json:json:jar:20250107:compile
[INFO] +- org.ehcache:ehcache:jar:3.10.8:compile
[INFO] +- commons-codec:commons-codec:jar:1.18.0:compile
[INFO] +- com.fasterxml.jackson.core:jackson-core:jar:2.18.2:compile
[INFO] +- com.sap.cds:cds-services-impl:jar:3.10.3:test
[INFO] |  +- com.sap.cds:cds-services-utils:jar:3.10.3:compile
[INFO] |  |  +- com.sap.cds:cds-adapter-api:jar:3.10.3:compile
[INFO] |  |  \- com.sap.cds:cds4j-runtime:jar:3.10.3:compile
[INFO] |  |     \- com.sap.cds:cds4j-jdbc-spi:jar:3.10.3:compile
[INFO] |  +- com.sap.cds:cds-services-messaging:jar:3.10.3:test
[INFO] |  |  \- jakarta.jms:jakarta.jms-api:jar:3.1.0:test
[INFO] |  \- com.sap.cds:cds4j-core:jar:3.10.3:compile
[INFO] +- junit:junit:jar:4.13.2:test
[INFO] +- com.squareup.okhttp3:okhttp:jar:5.0.0-alpha.14:compile
[INFO] |  +- com.squareup.okio:okio-jvm:jar:3.9.0:compile
[INFO] |  \- org.jetbrains.kotlin:kotlin-stdlib:jar:1.9.23:compile
[INFO] |     \- org.jetbrains:annotations:jar:13.0:compile
[INFO] +- com.squareup.okhttp3:mockwebserver:jar:5.0.0-alpha.14:test
[INFO] |  \- com.squareup.okhttp3:mockwebserver3:jar:5.0.0-alpha.14:test
[INFO] +- com.sap.cds:cds-feature-attachments:jar:1.0.9:compile
[INFO] |  \- com.sap.cloud.sdk.cloudplatform:cloudplatform-core:jar:5.21.0:compile
[INFO] +- com.sap.cloud.sdk.cloudplatform:connectivity-oauth:jar:5.21.0:compile
[INFO] |  +- com.sap.cloud.sdk.cloudplatform:cloudplatform-connectivity:jar:5.21.0:compile
[INFO] |  |  +- com.sap.cloud.sdk.cloudplatform:resilience-api:jar:5.21.0:compile
[INFO] |  |  +- com.mikesamuel:json-sanitizer:jar:1.2.3:compile
[INFO] |  |  +- org.bouncycastle:bcprov-jdk18on:jar:1.81:compile
[INFO] |  |  \- org.bouncycastle:bcpkix-jdk18on:jar:1.81:compile
[INFO] |  |     \- org.bouncycastle:bcutil-jdk18on:jar:1.81:compile (version selected from constraint [1.81,1.82))
[INFO] |  +- com.sap.cloud.sdk.cloudplatform:connectivity-apache-httpclient4:jar:5.21.0:compile
[INFO] |  +- com.sap.cloud.sdk.cloudplatform:security:jar:5.21.0:compile
[INFO] |  +- com.sap.cloud.sdk.cloudplatform:tenant:jar:5.21.0:compile
[INFO] |  +- com.sap.cloud.sdk.cloudplatform:caching:jar:5.21.0:compile
[INFO] |  +- com.sap.cloud.environment.servicebinding.api:java-consumption-api:jar:0.10.5:compile
[INFO] |  +- com.sap.cloud.sdk.cloudplatform:resilience:jar:5.21.0:compile
[INFO] |  |  \- com.sap.cloud.sdk.cloudplatform:resilience4j:jar:5.21.0:compile
[INFO] |  |     +- io.github.resilience4j:resilience4j-circuitbreaker:jar:2.3.0:compile
[INFO] |  |     |  \- io.github.resilience4j:resilience4j-core:jar:2.3.0:compile
[INFO] |  |     |     \- org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar:1.9.0:compile
[INFO] |  |     |        \- org.jetbrains.kotlin:kotlin-stdlib-jdk7:jar:1.9.0:compile
[INFO] |  |     +- io.github.resilience4j:resilience4j-bulkhead:jar:2.3.0:compile
[INFO] |  |     +- io.github.resilience4j:resilience4j-timelimiter:jar:2.3.0:compile
[INFO] |  |     +- io.github.resilience4j:resilience4j-retry:jar:2.3.0:compile
[INFO] |  |     +- io.github.resilience4j:resilience4j-ratelimiter:jar:2.3.0:compile
[INFO] |  |     \- javax.cache:cache-api:jar:1.1.1:compile
[INFO] |  +- org.slf4j:jcl-over-slf4j:jar:2.0.17:runtime
[INFO] |  +- com.auth0:java-jwt:jar:4.5.0:compile
[INFO] |  +- io.vavr:vavr:jar:0.10.6:compile
[INFO] |  |  \- io.vavr:vavr-match:jar:0.10.6:compile
[INFO] |  +- org.apache.commons:commons-lang3:jar:3.18.0:compile
[INFO] |  \- com.sap.cloud.security:java-security:jar:3.6.0:runtime
[INFO] |     +- com.sap.cloud.security:env:jar:3.6.0:runtime
[INFO] |     |  \- com.sap.cloud.environment.servicebinding:java-sap-service-operator:jar:0.10.5:runtime
[INFO] |     \- commons-io:commons-io:jar:2.19.0:runtime
[INFO] +- com.google.guava:guava:jar:33.4.0-jre:compile
[INFO] |  +- com.google.guava:failureaccess:jar:1.0.2:compile
[INFO] |  +- com.google.errorprone:error_prone_annotations:jar:2.40.0:compile
[INFO] |  \- com.google.j2objc:j2objc-annotations:jar:3.0.0:compile
[INFO] +- org.mockito:mockito-junit-jupiter:jar:5.15.2:test
[INFO] +- com.sap.cds:cds-starter-cloudfoundry:jar:3.10.3:compile
[INFO] |  +- com.sap.cds:cds-feature-hana:jar:3.10.3:compile
[INFO] |  |  \- com.sap.cloud.db.jdbc:ngdbc:jar:2.25.9:compile
[INFO] |  +- com.sap.cds:cds-feature-mt:jar:3.10.3:compile
[INFO] |  |  +- com.sap.cds:cds-integration-cloud-sdk:jar:3.10.3:compile
[INFO] |  |  \- com.google.code.gson:gson:jar:2.13.1:compile
[INFO] |  +- com.sap.cds:cds-feature-cloudfoundry:jar:3.10.3:compile
[INFO] |  |  \- com.sap.cloud.environment.servicebinding:java-sap-vcap-services:jar:0.10.5:compile
[INFO] |  +- com.sap.cds:cds-feature-identity:jar:3.10.3:compile
[INFO] |  \- com.sap.cloud.security:resourceserver-security-spring-boot-starter:jar:3.6.0:compile
[INFO] |     +- com.sap.cloud.security:spring-security:jar:3.6.0:compile
[INFO] |     +- org.springframework.security:spring-security-oauth2-jose:jar:6.4.4:compile
[INFO] |     |  \- org.springframework.security:spring-security-oauth2-core:jar:6.4.4:compile
[INFO] |     \- org.springframework.security:spring-security-oauth2-resource-server:jar:6.4.4:compile
[INFO] +- io.reactivex.rxjava2:rxjava:jar:2.2.21:compile
[INFO] |  \- org.reactivestreams:reactive-streams:jar:1.0.3:compile
[INFO] +- com.sap.cds:cds-services-api:jar:3.10.3:compile
[INFO] |  \- com.sap.cds:cds4j-api:jar:3.10.3:compile
[INFO] +- org.junit.jupiter:junit-jupiter-api:jar:5.11.3:test
[INFO] |  +- org.opentest4j:opentest4j:jar:1.3.0:test
[INFO] |  +- org.junit.platform:junit-platform-commons:jar:1.11.3:test
[INFO] |  \- org.apiguardian:apiguardian-api:jar:1.1.2:test
[INFO] +- org.assertj:assertj-core:jar:3.27.3:test
[INFO] +- net.bytebuddy:byte-buddy:jar:1.17.1:compile
[INFO] +- net.bytebuddy:byte-buddy-agent:jar:1.17.1:test
[INFO] +- org.mockito:mockito-core:jar:5.15.2:test
[INFO] \- org.apache.httpcomponents:httpmime:jar:4.5.14:compile
```
</details>

### Code Examples

```java
// Your code here
```

### Log File

[demoappjava-srv-2025-08-08 10_40_52.104+0000.txt](https://github.com/user-attachments/files/21695772/demoappjava-srv-2025-08-08.10_40_52.104%2B0000.txt)

### Affected Development Phase

Release

### Impact

Blocked

**Comment by yashmeet29** [comment]
Hi  @CharlesDuboisSAP, below is the dependency tree of my cap application

customer:demoapp:jar:1.0.0-SNAPSHOT
[INFO] +- com.sap.cds:sdm:jar:1.0.0-RC1:compile
[INFO] |  +- org.apache.httpcomponents.client5:httpclient5:jar:5.3.1:compile
[INFO] |  |  \- org.apache.httpcomponents.core5:httpcore5-h2:jar:5.2.4:compile
[INFO] |  +- org.apache.httpcomponents.core5:httpcore5:jar:5.2.4:compile
[INFO] |  +- org.apache.httpcomponents:httpasyncclient:jar:4.1.5:compile
[INFO] |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.16:compile
[INFO] |  |  +- org.apache.httpcomponents:httpcore-nio:jar:4.4.16:compile
[INFO] |  |  \- org.apache.httpcomponents:httpclient:jar:4.5.13:compile
[INFO] |  +- org.apache.logging.log4j:log4j-api:jar:2.23.1:compile
[INFO] |  +- com.sap.cloud.security.xsuaa:token-client:jar:3.5.7:compile
[INFO] |  |  \- com.github.ben-manes.caffeine:caffeine:jar:3.1.8:compile
[INFO] |  +- com.sap.cloud.security:java-api:jar:3.5.8:compile
[INFO] |  +- com.sap.cloud.environment.servicebinding.api:java-access-api:jar:0.10.5:compile
[INFO] |  +- com.sap.cloud.environment.servicebinding.api:java-core-api:jar:0.10.5:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.17.1:compile
[INFO] |  |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.17.1:compile
[INFO] |  +- org.json:json:jar:20250107:compile
[INFO] |  +- org.ehcache:ehcache:jar:3.10.8:compile
[INFO] |  +- commons-codec:commons-codec:jar:1.16.1:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-core:jar:2.17.1:compile
[INFO] |  +- com.squareup.okhttp3:okhttp:jar:4.12.0:compile
[INFO] |  |  +- com.squareup.okio:okio:jar:3.6.0:compile
[INFO] |  |  |  \- com.squareup.okio:okio-jvm:jar:3.6.0:compile
[INFO] |  |  |     \- org.jetbrains.kotlin:kotlin-stdlib-common:jar:1.9.24:compile
[INFO] |  |  \- org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar:1.9.24:compile
[INFO] |  |     +- org.jetbrains.kotlin:kotlin-stdlib:jar:1.9.24:compile
[INFO] |  |     |  \- org.jetbrains:annotations:jar:13.0:compile
[INFO] |  |     \- org.jetbrains.kotlin:kotlin-stdlib-jdk7:jar:1.9.24:compile
[INFO] |  +- com.sap.cds:cds-feature-attachments:jar:1.0.9:compile
[INFO] |  |  \- com.sap.cloud.sdk.cloudplatform:cloudplatform-core:jar:5.19.0:compile
[INFO] |  +- com.sap.cloud.sdk.cloudplatform:connectivity-oauth:jar:5.21.0:compile
[INFO] |  |  +- com.sap.cloud.sdk.cloudplatform:cloudplatform-connectivity:jar:5.21.0:compile
[INFO] |  |  |  +- com.sap.cloud.sdk.cloudplatform:resilience-api:jar:5.21.0:compile
[INFO] |  |  |  +- com.mikesamuel:json-sanitizer:jar:1.2.3:compile
[INFO] |  |  |  +- org.bouncycastle:bcprov-jdk18on:jar:1.81:compile
[INFO] |  |  |  \- org.bouncycastle:bcpkix-jdk18on:jar:1.81:compile
[INFO] |  |  |     \- org.bouncycastle:bcutil-jdk18on:jar:1.81:compile
[INFO] |  |  +- com.sap.cloud.sdk.cloudplatform:connectivity-apache-httpclient4:jar:5.21.0:compile
[INFO] |  |  +- com.sap.cloud.sdk.cloudplatform:security:jar:5.21.0:compile
[INFO] |  |  +- com.sap.cloud.sdk.cloudplatform:tenant:jar:5.21.0:compile
[INFO] |  |  +- com.sap.cloud.sdk.cloudplatform:caching:jar:5.21.0:compile
[INFO] |  |  +- com.sap.cloud.environment.servicebinding.api:java-consumption-api:jar:0.21.0:compile
[INFO] |  |  +- com.sap.cloud.sdk.cloudplatform:resilience:jar:5.21.0:compile
[INFO] |  |  |  \- com.sap.cloud.sdk.cloudplatform:resilience4j:jar:5.21.0:compile
[INFO] |  |  |     +- io.github.resilience4j:resilience4j-circuitbreaker:jar:2.3.0:compile
[INFO] |  |  |     |  \- io.github.resilience4j:resilience4j-core:jar:2.3.0:compile
[INFO] |  |  |     +- io.github.resilience4j:resilience4j-bulkhead:jar:2.3.0:compile
[INFO] |  |  |     +- io.github.resilience4j:resilience4j-timelimiter:jar:2.3.0:compile
[INFO] |  |  |     +- io.github.resilience4j:resilience4j-retry:jar:2.3.0:compile
[INFO] |  |  |     +- io.github.resilience4j:resilience4j-ratelimiter:jar:2.3.0:compile
[INFO] |  |  |     \- javax.cache:cache-api:jar:1.1.1:compile
[INFO] |  |  +- org.slf4j:jcl-over-slf4j:jar:2.0.13:runtime
[INFO] |  |  +- com.auth0:java-jwt:jar:4.5.0:compile
[INFO] |  |  +- io.vavr:vavr:jar:0.10.6:compile
[INFO] |  |  |  \- io.vavr:vavr-match:jar:0.10.6:compile
[INFO] |  |  +- org.apache.commons:commons-lang3:jar:3.14.0:compile
[INFO] |  |  \- com.sap.cloud.security:java-security:jar:3.6.0:runtime
[INFO] |  |     \- com.sap.cloud.security:env:jar:3.6.0:runtime
[INFO] |  |        \- com.sap.cloud.environment.servicebinding:java-sap-service-operator:jar:0.20.0:runtime
[INFO] |  +- com.google.guava:guava:jar:33.4.0-jre:compile
[INFO] |  |  +- com.google.guava:failureaccess:jar:1.0.2:compile
[INFO] |  |  +- com.google.errorprone:error_prone_annotations:jar:2.36.0:compile
[INFO] |  |  \- com.google.j2objc:j2objc-annotations:jar:3.0.0:compile
[INFO] |  +- com.sap.cds:cds-starter-cloudfoundry:jar:4.1.1:compile
[INFO] |  |  +- com.sap.cds:cds-feature-hana:jar:4.1.1:compile
[INFO] |  |  |  \- com.sap.cloud.db.jdbc:ngdbc:jar:2.25.9:compile
[INFO] |  |  +- com.sap.cds:cds-feature-mt:jar:4.1.1:compile
[INFO] |  |  |  +- com.sap.cds:cds-integration-cloud-sdk:jar:4.1.1:compile
[INFO] |  |  |  \- com.google.code.gson:gson:jar:2.10.1:compile
[INFO] |  |  +- com.sap.cds:cds-feature-cloudfoundry:jar:4.1.1:compile
[INFO] |  |  |  \- com.sap.cloud.environment.servicebinding:java-sap-vcap-services:jar:0.21.0:compile
[INFO] |  |  +- com.sap.cds:cds-feature-identity:jar:4.1.1:compile
[INFO] |  |  \- com.sap.cloud.security:resourceserver-security-spring-boot-starter:jar:3.6.0:compile
[INFO] |  |     +- com.sap.cloud.security:spring-security:jar:3.6.0:compile
[INFO] |  |     +- org.springframework.security:spring-security-oauth2-jose:jar:6.3.1:compile
[INFO] |  |     |  \- org.springframework.security:spring-security-oauth2-core:jar:6.3.1:compile
[INFO] |  |     \- org.springframework.security:spring-security-oauth2-resource-server:jar:6.3.1:compile
[INFO] |  +- io.reactivex.rxjava2:rxjava:jar:2.2.21:compile
[INFO] |  |  \- org.reactivestreams:reactive-streams:jar:1.0.4:compile
[INFO] |  +- com.sap.cds:cds-services-api:jar:4.1.1:compile
[INFO] |  |  \- com.sap.cds:cds4j-api:jar:4.1.1:compile
[INFO] |  +- net.bytebuddy:byte-buddy:jar:1.14.17:compile
[INFO] |  \- org.apache.httpcomponents:httpmime:jar:4.5.14:compile
[INFO] +- com.sap.cds:cds-starter-spring-boot:jar:4.1.1:compile
[INFO] |  +- com.sap.cds:cds-services-impl:jar:4.1.1:runtime
[INFO] |  |  +- com.sap.cds:cds-services-messaging:jar:4.1.1:runtime
[INFO] |  |  |  \- jakarta.jms:jakarta.jms-api:jar:3.1.0:runtime
[INFO] |  |  \- org.apache.commons:commons-csv:jar:1.14.0:runtime
[INFO] |  +- com.sap.cds:cds-feature-jdbc:jar:4.1.1:runtime
[INFO] |  |  +- com.sap.cds:cds4j-runtime:jar:4.1.1:compile
[INFO] |  |  |  \- com.sap.cds:cds4j-jdbc-spi:jar:4.1.1:compile
[INFO] |  |  \- com.sap.cds:cds4j-tx:jar:4.1.1:runtime
[INFO] |  +- com.sap.cds:cds-framework-spring-boot:jar:4.1.1:runtime
[INFO] |  +- org.springframework.boot:spring-boot-starter-web:jar:3.3.1:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-json:jar:3.3.1:compile
[INFO] |  |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.17.1:compile
[INFO] |  |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.17.1:compile
[INFO] |  |  |  \- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.17.1:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-tomcat:jar:3.3.1:compile
[INFO] |  |  |  +- org.apache.tomcat.embed:tomcat-embed-core:jar:10.1.25:compile
[INFO] |  |  |  +- org.apache.tomcat.embed:tomcat-embed-el:jar:10.1.25:compile
[INFO] |  |  |  \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:10.1.25:compile
[INFO] |  |  +- org.springframework:spring-web:jar:6.1.10:compile
[INFO] |  |  |  \- io.micrometer:micrometer-observation:jar:1.13.1:compile
[INFO] |  |  |     \- io.micrometer:micrometer-commons:jar:1.13.1:compile
[INFO] |  |  \- org.springframework:spring-webmvc:jar:6.1.10:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-jdbc:jar:3.3.1:compile
[INFO] |  |  +- com.zaxxer:HikariCP:jar:5.1.0:compile
[INFO] |  |  \- org.springframework:spring-jdbc:jar:6.1.10:compile
[INFO] |  |     \- org.springframework:spring-tx:jar:6.1.10:compile
[INFO] |  \- org.yaml:snakeyaml:jar:2.2:compile
[INFO] +- com.sap.cds:cds-adapter-odata-v4:jar:4.1.1:runtime
[INFO] |  +- com.sap.cds:cds-adapter-api:jar:4.1.1:compile
[INFO] |  +- com.sap.cds:cds-services-utils:jar:4.1.1:compile
[INFO] |  |  +- commons-io:commons-io:jar:2.19.0:compile
[INFO] |  |  \- io.opentelemetry:opentelemetry-api:jar:1.37.0:compile
[INFO] |  |     \- io.opentelemetry:opentelemetry-context:jar:1.37.0:compile
[INFO] |  +- com.sap.cds:cds4j-core:jar:4.1.1:compile
[INFO] |  +- com.sap.cds.repackaged:odata-v4-lib:jar:4.1.1:runtime
[INFO] |  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-xml:jar:2.17.1:runtime
[INFO] |  |  |  \- org.codehaus.woodstox:stax2-api:jar:4.2.2:runtime
[INFO] |  |  \- com.fasterxml:aalto-xml:jar:1.3.3:runtime
[INFO] |  \- org.slf4j:slf4j-api:jar:2.0.13:compile
[INFO] +- org.springframework.boot:spring-boot-devtools:jar:3.3.1:compile (optional)
[INFO] |  +- org.springframework.boot:spring-boot:jar:3.3.1:compile
[INFO] |  |  \- org.springframework:spring-context:jar:6.1.10:compile
[INFO] |  \- org.springframework.boot:spring-boot-autoconfigure:jar:3.3.1:compile
[INFO] +- org.springframework.boot:spring-boot-starter-test:jar:3.3.1:test
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:3.3.1:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-logging:jar:3.3.1:compile
[INFO] |  |  |  +- ch.qos.logback:logback-classic:jar:1.5.6:compile
[INFO] |  |  |  |  \- ch.qos.logback:logback-core:jar:1.5.6:compile
[INFO] |  |  |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.23.1:compile
[INFO] |  |  |  \- org.slf4j:jul-to-slf4j:jar:2.0.13:compile
[INFO] |  |  \- jakarta.annotation:jakarta.annotation-api:jar:2.1.1:compile
[INFO] |  +- org.springframework.boot:spring-boot-test:jar:3.3.1:test
[INFO] |  +- org.springframework.boot:spring-boot-test-autoconfigure:jar:3.3.1:test
[INFO] |  +- com.jayway.jsonpath:json-path:jar:2.9.0:test
[INFO] |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:4.0.2:test
[INFO] |  |  \- jakarta.activation:jakarta.activation-api:jar:2.1.3:test
[INFO] |  +- net.minidev:json-smart:jar:2.5.1:test
[INFO] |  |  \- net.minidev:accessors-smart:jar:2.5.1:test
[INFO] |  |     \- org.ow2.asm:asm:jar:9.6:test
[INFO] |  +- org.assertj:assertj-core:jar:3.25.3:test
[INFO] |  +- org.awaitility:awaitility:jar:4.2.1:test
[INFO] |  +- org.hamcrest:hamcrest:jar:2.2:test
[INFO] |  +- org.junit.jupiter:junit-jupiter:jar:5.10.2:test
[INFO] |  |  +- org.junit.jupiter:junit-jupiter-api:jar:5.10.2:test
[INFO] |  |  |  +- org.opentest4j:opentest4j:jar:1.3.0:test
[INFO] |  |  |  +- org.junit.platform:junit-platform-commons:jar:1.10.2:test
[INFO] |  |  |  \- org.apiguardian:apiguardian-api:jar:1.1.2:test
[INFO] |  |  +- org.junit.jupiter:junit-jupiter-params:jar:5.10.2:test
[INFO] |  |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.10.2:test
[INFO] |  |     \- org.junit.platform:junit-platform-engine:jar:1.10.2:test
[INFO] |  +- org.mockito:mockito-core:jar:5.11.0:test
[INFO] |  |  +- net.bytebuddy:byte-buddy-agent:jar:1.14.17:test
[INFO] |  |  \- org.objenesis:objenesis:jar:3.3:test
[INFO] |  +- org.mockito:mockito-junit-jupiter:jar:5.11.0:test
[INFO] |  +- org.skyscreamer:jsonassert:jar:1.5.1:test
[INFO] |  |  \- com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1:test
[INFO] |  +- org.springframework:spring-core:jar:6.1.10:compile
[INFO] |  |  \- org.springframework:spring-jcl:jar:6.1.10:compile
[INFO] |  +- org.springframework:spring-test:jar:6.1.10:test
[INFO] |  \- org.xmlunit:xmlunit-core:jar:2.9.1:test
[INFO] +- com.h2database:h2:jar:2.2.224:runtime
[INFO] \- org.springframework.boot:spring-boot-starter-security:jar:3.3.1:compile
[INFO]    +- org.springframework:spring-aop:jar:6.1.10:compile
[INFO]    |  \- org.springframework:spring-beans:jar:6.1.10:compile
[INFO]    +- org.springframework.security:spring-security-config:jar:6.3.1:compile
[INFO]    |  \- org.springframework.security:spring-security-core:jar:6.3.1:compile
[INFO]    |     \- org.springframework.security:spring-security-crypto:jar:6.3.1:compile
[INFO]    \- org.springframework.security:spring-security-web:jar:6.3.1:compile
[INFO]       \- org.springframework:spring-expression:jar:6.1.10:compile

Regards,
Yashmeet

**Comment by CharlesDuboisSAP** [comment]
Do not override the version for `cloudplatform-core`, please use the [`sdk-bom`](https://sap.github.io/cloud-sdk/docs/java/guides/manage-dependencies) instead to have one version tag for all Cloud SDK dependencies
