### ISSUE TITLE
IncompatibleClassChangeError since update to 5.25.0

### ISSUE THREAD

**Issue by CMNiedermayer** [SAP/cloud-sdk-java#1054]
### Describe the Bug

The following error occurs when trying to get a destination:
```
Caused by: java.lang.IncompatibleClassChangeError: Class com.google.common.base.Functions$IdentityFunction does not implement the requested interface java.util.function.Function
	at io.vavr.collection.StreamModule$FlatMapIterator.hasNext(Stream.java:2163)
	at io.vavr.collection.StreamModule$StreamFactory.create(Stream.java:2122)
	at io.vavr.collection.Stream.ofAll(Stream.java:391)
	at io.vavr.collection.Stream.flatMap(Stream.java:1067)
	at com.sap.cloud.sdk.cloudplatform.connectivity.GetOrComputeSingleDestinationCommand.authTokenIsExpired(GetOrComputeSingleDestinationCommand.java:289)
	at com.sap.cloud.sdk.cloudplatform.connectivity.GetOrComputeSingleDestinationCommand.getCachedDestination(GetOrComputeSingleDestinationCommand.java:241)
	at com.sap.cloud.sdk.cloudplatform.connectivity.GetOrComputeSingleDestinationCommand.execute(GetOrComputeSingleDestinationCommand.java:138)
	at io.vavr.control.Try.flatMapTry(Try.java:489)
	at io.vavr.control.Try.flatMap(Try.java:471)
	at com.sap.cloud.sdk.cloudplatform.connectivity.DestinationService$Cache.getOrComputeDestination(DestinationService.java:870)
	at com.sap.cloud.sdk.cloudplatform.connectivity.DestinationService.tryGetDestination(DestinationService.java:123)
	at com.sap.cloud.sdk.cloudplatform.connectivity.DestinationLoaderChain.tryGetDestination(DestinationLoaderChain.java:85)
	at com.sap.cloud.sdk.cloudplatform.connectivity.DestinationLoader.tryGetDestination(DestinationLoader.java:33)
	at com.sap.cloud.sdk.cloudplatform.connectivity.DestinationAccessor.tryGetDestination(DestinationAccessor.java:120)
```
### Steps to Reproduce

1. Retrieve a destination using Cloud SDK 5.24.0
2. Update Cloud SDK to 5.25.0
3. You will see the error

### Expected Behavior

It should work in 5.25.0 as well

### Used Versions

- Java and Maven version via `mvn --version`: 3.9.8
- SAP Cloud SDK version: 5.25.0
- Spring Boot or CAP version: Spring Boot 3.5.9 and CAP 4.6.1

<details><summary>Dependency tree via <code>mvn dependency:tree</code></summary>
    
```
Dependency tree here
```
</details>

I do not like to share the dependency in public. Please contact me directly. Obviously there seems to be a problem with the versions of Guava and VAVR.

### Code Examples

```java
// Your code here
```

### Log File

<details><summary>Log file</summary>
...
</details>

### Affected Development Phase

Getting Started

### Impact

No Impact

**Comment by newtork** [comment]
What version of guava are you using?
Please respect issue template by providing (part of) `mvn dependency:tree`  (or similar)

**Comment by CMNiedermayer** [comment]
@newtork Currently Guava 33.3.1-jre is inherited from the parent POM, most probably it comes via Spring. I am currently trying to enforce the usage of Guava 33.5.0-jre because I can see that the Cloud SDK is expecting that.

It looks like there was an incompatible change in Guava and instead of using java.util.function.Function the latest version uses com.google.common.base.Function now.

I will let you know about the outcome.
