### ISSUE TITLE
NoSuchMethodError after upgrade to 5.21.0

### ISSUE THREAD

**Issue by rakeshreddygundala** [SAP/cloud-sdk-java#883]
### Describe the Bug

NoSuchMethodError after upgrade to 5.21.0

### Steps to Reproduce

After we upgrade 'cloud-sdk-datamodel-openapi-generator-maven-plugin.version' from 5.20.0 to 5.21.0, we are noticing an error when we do build of our project.

Execution default of goal com.sap.cloud.sdk.datamodel:openapi-generator-maven-plugin:5.21.0:generate failed: An API incompatibility was encountered while executing com.sap.cloud.sdk.datamodel:openapi-generator-maven-plugin:5.21.0:generate: java.lang.NoSuchMethodError: 'com.fasterxml.jackson.annotation.OptBoolean com.fasterxml.jackson.annotation.JsonProperty.isRequired()'
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.sap.cloud.sdk.datamodel:openapi-generator-maven-plugin:5.21.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy

[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

### Expected Behavior

Post upgrade to 5.21.0, there should not be any build failure

### Used Versions

- Java and Maven version via `mvn --version`: 
Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)
Maven home: /opt/homebrew/Cellar/maven/3.9.9/libexec
Java version: 17.0.7, vendor: SAP SE, runtime: /Users/I306716/Library/Java/sapmachine-jdk-17.0.7.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "15.6", arch: "x86_64", family: "mac"

- SAP Cloud SDK version: 5.21.0
- Spring Boot or CAP version: 3.5

### Log File

<details><summary>Log file</summary>
...
</details>

### Affected Development Phase

Getting Started

### Impact

No Impact

**Comment by newtork** [comment]
I don't understand how that's possible, the plugin should have dependency `com.fasterxml.jackson.core:jackson-annotations:2.19.2`. However your error message indicates a version `<2.19.0`. Do you override the plugin dependency versions? Or enforce an older version of `jackson-annotations`?
* It could be worth checking dependency tree to identify `jackson-annotation` version.
* If you are brave you could also try and record the logs from the plugin execution, via `--debug`.

**Comment by rakeshreddygundala** [comment]
[ERROR] Failed to execute goal com.sap.cloud.sdk.datamodel:openapi-generator-maven-plugin:5.21.0:generate (default) on project reporting-foundation-service: Execution default of goal com.sap.cloud.sdk.datamodel:openapi-generator-maven-plugin:5.21.0:generate failed: An API incompatibility was encountered while executing com.sap.cloud.sdk.datamodel:openapi-generator-maven-plugin:5.21.0:generate: java.lang.NoSuchMethodError: 'com.fasterxml.jackson.annotation.OptBoolean com.fasterxml.jackson.annotation.JsonProperty.isRequired()'
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.sap.cloud.sdk.datamodel:openapi-generator-maven-plugin:5.21.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/Users/I306716/.m2/repository/com/sap/cloud/sdk/datamodel/openapi-generator-maven-plugin/5.21.0/openapi-generator-maven-plugin-5.21.0.jar
[ERROR] urls[1] = file:/Users/I306716/.m2/repository/com/sap/cloud/sdk/datamodel/openapi-generator/5.21.0/openapi-generator-5.21.0.jar
[ERROR] urls[2] = file:/Users/I306716/.m2/repository/com/sap/cloud/sdk/datamodel/datamodel-metadata-generator/5.21.0/datamodel-metadata-generator-5.21.0.jar
[ERROR] urls[3] = file:/Users/I306716/.m2/repository/com/sap/cloud/sdk/cloudplatform/connectivity-apache-httpclient4/5.21.0/connectivity-apache-httpclient4-5.21.0.jar
[ERROR] urls[4] = file:/Users/I306716/.m2/repository/com/sap/cloud/sdk/cloudplatform/caching/5.21.0/caching-5.21.0.jar
[ERROR] urls[5] = file:/Users/I306716/.m2/repository/com/sap/cloud/sdk/cloudplatform/tenant/5.21.0/tenant-5.21.0.jar
[ERROR] urls[6] = file:/Users/I306716/.m2/repository/com/google/code/gson/gson/2.13.1/gson-2.13.1.jar
[ERROR] urls[7] = file:/Users/I306716/.m2/repository/org/apache/httpcomponents/httpclient/4.5.14/httpclient-4.5.14.jar
[ERROR] urls[8] = file:/Users/I306716/.m2/repository/commons-codec/commons-codec/1.11/commons-codec-1.11.jar
[ERROR] urls[9] = file:/Users/I306716/.m2/repository/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar
[ERROR] urls[10] = file:/Users/I306716/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-xml/2.19.1/jackson-dataformat-xml-2.19.1.jar
[ERROR] urls[11] = file:/Users/I306716/.m2/repository/org/codehaus/woodstox/stax2-api/4.2.2/stax2-api-4.2.2.jar
[ERROR] urls[12] = file:/Users/I306716/.m2/repository/com/fasterxml/woodstox/woodstox-core/7.1.1/woodstox-core-7.1.1.jar
[ERROR] urls[13] = file:/Users/I306716/.m2/repository/com/thoughtworks/qdox/qdox/2.2.0/qdox-2.2.0.jar
[ERROR] urls[14] = file:/Users/I306716/.m2/repository/com/sap/cloud/sdk/cloudplatform/cloudplatform-connectivity/5.21.0/cloudplatform-connectivity-5.21.0.jar
[ERROR] urls[15] = file:/Users/I306716/.m2/repository/com/sap/cloud/sdk/cloudplatform/resilience-api/5.21.0/resilience-api-5.21.0.jar
[ERROR] urls[16] = file:/Users/I306716/.m2/repository/com/sap/cloud/sdk/cloudplatform/security/5.21.0/security-5.21.0.jar
[ERROR] urls[17] = file:/Users/I306716/.m2/repository/com/sap/cloud/environment/servicebinding/api/java-core-api/0.21.0/java-core-api-0.21.0.jar
[ERROR] urls[18] = file:/Users/I306716/.m2/repository/com/sap/cloud/environment/servicebinding/api/java-access-api/0.21.0/java-access-api-0.21.0.jar
[ERROR] urls[19] = file:/Users/I306716/.m2/repository/org/slf4j/jcl-over-slf4j/2.0.17/jcl-over-slf4j-2.0.17.jar
[ERROR] urls[20] = file:/Users/I306716/.m2/repository/com/mikesamuel/json-sanitizer/1.2.3/json-sanitizer-1.2.3.jar
[ERROR] urls[21] = file:/Users/I306716/.m2/repository/org/apache/commons/commons-lang3/3.18.0/commons-lang3-3.18.0.jar
[ERROR] urls[22] = file:/Users/I306716/.m2/repository/com/auth0/java-jwt/4.5.0/java-jwt-4.5.0.jar
[ERROR] urls[23] = file:/Users/I306716/.m2/repository/org/bouncycastle/bcprov-jdk18on/1.81/bcprov-jdk18on-1.81.jar
[ERROR] urls[24] = file:/Users/I306716/.m2/repository/org/bouncycastle/bcpkix-jdk18on/1.81/bcpkix-jdk18on-1.81.jar
[ERROR] urls[25] = file:/Users/I306716/.m2/repository/org/bouncycastle/bcutil-jdk18on/1.81/bcutil-jdk18on-1.81.jar
[ERROR] urls[26] = file:/Users/I306716/.m2/repository/com/sap/cloud/sdk/cloudplatform/cloudplatform-core/5.21.0/cloudplatform-core-5.21.0.jar
[ERROR] urls[27] = file:/Users/I306716/.m2/repository/org/openapitools/openapi-generator/7.14.0/openapi-generator-7.14.0.jar
[ERROR] urls[28] = file:/Users/I306716/.m2/repository/com/samskivert/jmustache/1.15/jmustache-1.15.jar
[ERROR] urls[29] = file:/Users/I306716/.m2/repository/com/github/jknack/handlebars/4.3.1/handlebars-4.3.1.jar
[ERROR] urls[30] = file:/Users/I306716/.m2/repository/com/github/jknack/handlebars-jackson2/4.3.1/handlebars-jackson2-4.3.1.jar
[ERROR] urls[31] = file:/Users/I306716/.m2/repository/org/slf4j/slf4j-ext/1.7.36/slf4j-ext-1.7.36.jar
[ERROR] urls[32] = file:/Users/I306716/.m2/repository/org/apache/commons/commons-text/1.10.0/commons-text-1.10.0.jar
[ERROR] urls[33] = file:/Users/I306716/.m2/repository/commons-cli/commons-cli/1.5.0/commons-cli-1.5.0.jar
[ERROR] urls[34] = file:/Users/I306716/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-guava/2.18.2/jackson-datatype-guava-2.18.2.jar
[ERROR] urls[35] = file:/Users/I306716/.m2/repository/org/commonmark/commonmark/0.21.0/commonmark-0.21.0.jar
[ERROR] urls[36] = file:/Users/I306716/.m2/repository/com/github/mifmif/generex/1.0.2/generex-1.0.2.jar
[ERROR] urls[37] = file:/Users/I306716/.m2/repository/dk/brics/automaton/automaton/1.11-8/automaton-1.11-8.jar
[ERROR] urls[38] = file:/Users/I306716/.m2/repository/com/github/curious-odd-man/rgxgen/1.4/rgxgen-1.4.jar
[ERROR] urls[39] = file:/Users/I306716/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-joda/2.18.2/jackson-datatype-joda-2.18.2.jar
[ERROR] urls[40] = file:/Users/I306716/.m2/repository/joda-time/joda-time/2.12.7/joda-time-2.12.7.jar
[ERROR] urls[41] = file:/Users/I306716/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.18.2/jackson-annotations-2.18.2.jar
[ERROR] urls[42] = file:/Users/I306716/.m2/repository/com/github/joschi/jackson/jackson-datatype-threetenbp/2.18.2/jackson-datatype-threetenbp-2.18.2.jar
[ERROR] urls[43] = file:/Users/I306716/.m2/repository/org/threeten/threetenbp/1.7.0/threetenbp-1.7.0.jar
[ERROR] urls[44] = file:/Users/I306716/.m2/repository/org/openapitools/openapi-generator-core/7.14.0/openapi-generator-core-7.14.0.jar
[ERROR] urls[45] = file:/Users/I306716/.m2/repository/net/java/dev/jna/jna/5.12.1/jna-5.12.1.jar
[ERROR] urls[46] = file:/Users/I306716/.m2/repository/com/github/ben-manes/caffeine/caffeine/2.9.3/caffeine-2.9.3.jar
[ERROR] urls[47] = file:/Users/I306716/.m2/repository/org/checkerframework/checker-qual/3.19.0/checker-qual-3.19.0.jar
[ERROR] urls[48] = file:/Users/I306716/.m2/repository/org/projectlombok/lombok/1.18.30/lombok-1.18.30.jar
[ERROR] urls[49] = file:/Users/I306716/.m2/repository/org/yaml/snakeyaml/2.4/snakeyaml-2.4.jar
[ERROR] urls[50] = file:/Users/I306716/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.19.1/jackson-core-2.19.1.jar
[ERROR] urls[51] = file:/Users/I306716/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.19.1/jackson-dataformat-yaml-2.19.1.jar
[ERROR] urls[52] = file:/Users/I306716/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.19.1/jackson-databind-2.19.1.jar
[ERROR] urls[53] = file:/Users/I306716/.m2/repository/com/google/guava/guava/33.4.8-jre/guava-33.4.8-jre.jar
[ERROR] urls[54] = file:/Users/I306716/.m2/repository/com/google/guava/failureaccess/1.0.3/failureaccess-1.0.3.jar
[ERROR] urls[55] = file:/Users/I306716/.m2/repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
[ERROR] urls[56] = file:/Users/I306716/.m2/repository/org/jspecify/jspecify/1.0.0/jspecify-1.0.0.jar
[ERROR] urls[57] = file:/Users/I306716/.m2/repository/com/google/errorprone/error_prone_annotations/2.36.0/error_prone_annotations-2.36.0.jar
[ERROR] urls[58] = file:/Users/I306716/.m2/repository/com/google/j2objc/j2objc-annotations/3.0.0/j2objc-annotations-3.0.0.jar
[ERROR] urls[59] = file:/Users/I306716/.m2/repository/commons-io/commons-io/2.19.0/commons-io-2.19.0.jar
[ERROR] urls[60] = file:/Users/I306716/.m2/repository/io/swagger/core/v3/swagger-models/2.2.34/swagger-models-2.2.34.jar
[ERROR] urls[61] = file:/Users/I306716/.m2/repository/io/swagger/parser/v3/swagger-parser/2.1.31/swagger-parser-2.1.31.jar
[ERROR] urls[62] = file:/Users/I306716/.m2/repository/io/swagger/parser/v3/swagger-parser-v2-converter/2.1.31/swagger-parser-v2-converter-2.1.31.jar
[ERROR] urls[63] = file:/Users/I306716/.m2/repository/io/swagger/swagger-core/1.6.16/swagger-core-1.6.16.jar
[ERROR] urls[64] = file:/Users/I306716/.m2/repository/jakarta/xml/bind/jakarta.xml.bind-api/2.3.3/jakarta.xml.bind-api-2.3.3.jar
[ERROR] urls[65] = file:/Users/I306716/.m2/repository/jakarta/activation/jakarta.activation-api/1.2.2/jakarta.activation-api-1.2.2.jar
[ERROR] urls[66] = file:/Users/I306716/.m2/repository/io/swagger/swagger-models/1.6.16/swagger-models-1.6.16.jar
[ERROR] urls[67] = file:/Users/I306716/.m2/repository/io/swagger/swagger-annotations/1.6.16/swagger-annotations-1.6.16.jar
[ERROR] urls[68] = file:/Users/I306716/.m2/repository/io/swagger/swagger-parser/1.0.75/swagger-parser-1.0.75.jar
[ERROR] urls[69] = file:/Users/I306716/.m2/repository/io/swagger/swagger-parser-safe-url-resolver/1.0.75/swagger-parser-safe-url-resolver-1.0.75.jar
[ERROR] urls[70] = file:/Users/I306716/.m2/repository/io/swagger/swagger-compat-spec-parser/1.0.75/swagger-compat-spec-parser-1.0.75.jar
[ERROR] urls[71] = file:/Users/I306716/.m2/repository/com/github/java-json-tools/json-schema-validator/2.2.14/json-schema-validator-2.2.14.jar
[ERROR] urls[72] = file:/Users/I306716/.m2/repository/com/github/java-json-tools/jackson-coreutils-equivalence/1.0/jackson-coreutils-equivalence-1.0.jar
[ERROR] urls[73] = file:/Users/I306716/.m2/repository/com/github/java-json-tools/json-schema-core/1.2.14/json-schema-core-1.2.14.jar
[ERROR] urls[74] = file:/Users/I306716/.m2/repository/com/github/java-json-tools/uri-template/0.10/uri-template-0.10.jar
[ERROR] urls[75] = file:/Users/I306716/.m2/repository/org/mozilla/rhino/1.7.7.2/rhino-1.7.7.2.jar
[ERROR] urls[76] = file:/Users/I306716/.m2/repository/com/googlecode/libphonenumber/libphonenumber/8.11.1/libphonenumber-8.11.1.jar
[ERROR] urls[77] = file:/Users/I306716/.m2/repository/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
[ERROR] urls[78] = file:/Users/I306716/.m2/repository/com/github/java-json-tools/json-patch/1.13/json-patch-1.13.jar
[ERROR] urls[79] = file:/Users/I306716/.m2/repository/com/github/java-json-tools/msg-simple/1.2/msg-simple-1.2.jar
[ERROR] urls[80] = file:/Users/I306716/.m2/repository/com/github/java-json-tools/btf/1.3/btf-1.3.jar
[ERROR] urls[81] = file:/Users/I306716/.m2/repository/com/github/java-json-tools/jackson-coreutils/2.0/jackson-coreutils-2.0.jar
[ERROR] urls[82] = file:/Users/I306716/.m2/repository/io/swagger/parser/v3/swagger-parser-v3/2.1.31/swagger-parser-v3-2.1.31.jar
[ERROR] urls[83] = file:/Users/I306716/.m2/repository/io/swagger/core/v3/swagger-core/2.2.34/swagger-core-2.2.34.jar
[ERROR] urls[84] = file:/Users/I306716/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.18.2/jackson-datatype-jsr310-2.18.2.jar
[ERROR] urls[85] = file:/Users/I306716/.m2/repository/io/swagger/core/v3/swagger-annotations/2.2.34/swagger-annotations-2.2.34.jar
[ERROR] urls[86] = file:/Users/I306716/.m2/repository/jakarta/validation/jakarta.validation-api/2.0.2/jakarta.validation-api-2.0.2.jar
[ERROR] urls[87] = file:/Users/I306716/.m2/repository/io/swagger/parser/v3/swagger-parser-safe-url-resolver/2.1.31/swagger-parser-safe-url-resolver-2.1.31.jar
[ERROR] urls[88] = file:/Users/I306716/.m2/repository/io/swagger/parser/v3/swagger-parser-core/2.1.31/swagger-parser-core-2.1.31.jar
[ERROR] urls[89] = file:/Users/I306716/.m2/repository/io/vavr/vavr/0.10.6/vavr-0.10.6.jar
[ERROR] urls[90] = file:/Users/I306716/.m2/repository/io/vavr/vavr-match/0.10.6/vavr-match-0.10.6.jar
[ERROR] urls[91] = file:/Users/I306716/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------

**Comment by rakeshreddygundala** [comment]
➜  reporting-foundation-service git:(renovate/update-non-major-dependencies) mvn dependency:tree | grep jackson-annotations
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.19.1:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.19.1:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.19.1:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.19.1:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.19.1:compile

**Comment by rakeshreddygundala** [comment]
with version '5.20.0' for 'cloud-sdk-datamodel-openapi-generator-maven-plugin.version', everything is fine but when we upgrade to '5.21.0', then we get this build issue w.r.t jackson dependancy.

**Comment by CharlesDuboisSAP** [comment]
What command are you using to run the generator, could you also run the dependency tree without grep in the same terminal as the generator command.

**Comment by rakeshreddygundala** [comment]
<plugin>
        <groupId>com.sap.cloud.sdk.datamodel</groupId>
        <artifactId>openapi-generator-maven-plugin</artifactId>
        <version>5.21.0</version>
        <configuration>
          <inputSpec>${project.basedir}/yaml/SAC_API.yaml</inputSpec>
          <outputDirectory>${project.build.directory}/generated-sources/java</outputDirectory>
          <deleteOutputDirectory>true</deleteOutputDirectory>
          <apiPackage>com.sap.sac.api</apiPackage>
          <modelPackage>com.sap.sac.model</modelPackage>
          <apiMaturity>released</apiMaturity>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>generate</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

**Comment by rakeshreddygundala** [comment]
```xml
<plugin>
    <groupId>com.sap.cloud.sdk.datamodel</groupId>
    <artifactId>openapi-generator-maven-plugin</artifactId>
    <version>5.21.0</version>
    <configuration>
        <inputSpec>${project.basedir}/yaml/SAC_API.yaml</inputSpec>
        <outputDirectory>${project.build.directory}/generated-sources/java</outputDirectory>
        <deleteOutputDirectory>true</deleteOutputDirectory>
        <apiPackage>com.sap.sac.api</apiPackage>
        <modelPackage>com.sap.sac.model</modelPackage>
        <apiMaturity>released</apiMaturity>
    </configuration>
    <executions>
        <execution>
            <goals>
                <goal>generate</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

**Comment by rakeshreddygundala** [comment]
[

[dependancy.log](https://github.com/user-attachments/files/21724306/dependancy.log)

](url)

**Comment by rakeshreddygundala-ai** [comment]
problem is not solved, please help.

**Comment by rakeshreddygundala-ai** [comment]
which version of jackson to be used post upgrade of 5.21.0? for us 'openapi-generator-maven-plugin' is failing with error .

[ERROR] Failed to execute goal com.sap.cloud.sdk.datamodel:openapi-generator-maven-plugin:5.21.0:generate (default) on project reporting-foundation-service: Execution default of goal com.sap.cloud.sdk.datamodel:openapi-generator-maven-plugin:5.21.0:generate failed: An API incompatibility was encountered while executing com.sap.cloud.sdk.datamodel:openapi-generator-maven-plugin:5.21.0:generate: java.lang.NoSuchMethodError: 'com.fasterxml.jackson.annotation.OptBoolean com.fasterxml.jackson.annotation.JsonProperty.isRequired()'
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.sap.cloud.sdk.datamodel:openapi-generator-maven-plugin:5.21.0

**Comment by CharlesDuboisSAP** [comment]
We use jackson `2.19.1` in both releases. I generated in a test project with both releases without a problem.

**Comment by CharlesDuboisSAP** [comment]
2.19.2 support will come in the next release of Cloud SDK, but it shouldn't be an issue as we use it in our SNAPSHOT

**Comment by newtork** [comment]
FYI we reproduced and fixed the observed exception when using Swagger v2 specification file for our `openapi-generator-plugin:5.21.0`.

> java.lang.NoSuchMethodError: 'com.fasterxml.jackson.annotation.OptBoolean com.fasterxml.jackson.annotation.JsonProperty.isRequired()'

With the next release `5.22.0`, hopefully your application works as well as it did for `5.20.0`.
Sorry for the inconvenience.
